### ISSUE TITLE
Wrong contact for SDM-RDFizer

### ISSUE THREAD

**Issue by arenas-guerrero-julian** [RMLio/rml-test-cases#57]
Hi,

I just noticed that the contact person for SDM-RDZFizer in the RML implementation report (Unofficial Draft 03 January 2022) is possibly wrong .

Julián

**Comment by bjdmeest** [comment]
Totally my bad, copy-pasted poorly, a PR is already present, thanks for notifying! https://github.com/RMLio/rml-implementation-report/pull/36

**Comment by arenas-guerrero-julian** [comment]
Can this be closed?
